keys:
  # Age public key derived from rhea's SSH host key.
  # After the first nixos-install, run:
  #   nix-shell -p ssh-to-age --run 'ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub'
  # and replace the placeholder below.
  - &rhea age1REPLACEME

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *rhea
